#!/usr/bin/python3
#
# This script will take the information created by user_data
# and generate an ansible inventory file
#
#
# The tools we'll use
import os
import configparser
info = configparser.ConfigParser()


# Open config file generated by Terraform
info.read('/provisioning_info.txt')

# Load our variables from the configuration file, split them when necessary
lab = info.get('DEFAULT', 'lab')
master_hostnames = info.get('DEFAULT', 'master_hostnames').split(",")
worker_hostnames = info.get('DEFAULT', 'worker_hostnames').split(",")

# Create output dir
if not os.path.exists('./output'):
    os.mkdir('./output')

# Write our host entries to a file
hosts = open("./output/ansible_hosts.txt", "w")

# Create our ansible hosts file entries for master nodes
hosts.write(f"[masters]\n")

i = 0
while(i < len(master_hostnames)):
    hosts.write(f"{master_hostnames[i]}\n")
    i += 1

# Put 1 new line between the sections (masters & workers)
hosts.write("\n")

# Create our ansible hosts file entries for worker nodes
hosts.write(f"[workers]\n")

i = 0
while(i < len(worker_hostnames)):
    hosts.write(f"{worker_hostnames[i]}\n")
    i += 1

# Create localhost entry for bastion host
hosts.write(f"\n")
hosts.write(f"[bastion]\n")
hosts.write(f"localhost")

# Close file
hosts.close()