---
- hosts: masters
  become: yes
  remote_user: ec2-user
  tasks:
  - name: yum - Install kubeadm
    yum:
      name: kubeadm-1.24.7
      state: latest
      update_cache: yes
  
  - name: yum - Install kubectl
    yum:
      name: kubectl-1.24.7
      state: latest
      update_cache: yes
  
  - name: k8s - Initialize cluster
    shell: kubeadm init --pod-network-cidr=192.168.0.0/16

  - name: Creating .kube directory for ec2-user
    file:
      path: /home/ec2-user/.kube
      state: directory
      mode: 0755
      owner: ec2-user
      group: ec2-user

  - name: Copying admin.conf to ec2-user directory
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/ec2-user/.kube/config
      remote_src: yes
      owner: ec2-user
      group: ec2-user

  - name: Pausing for 15 seconds before deploying pod network
    pause:
      seconds: 15

  - name: Installing calico pod network
    become: yes
    become_user: ec2-user
    shell: |
          kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/tigera-operator.yaml
          kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/custom-resources.yaml
    
  - name: Getting token and join command for worker nodes
    become: yes
    become_user: ec2-user
    shell: kubeadm token create --print-join-command
    register: k8s_worker_join_command

  - name: Copying join command to file
    delegate_to: localhost
    copy:
      content: "{{k8s_worker_join_command.stdout_lines[0]}}"
      dest: "/home/ec2-user/k8s_join_command.sh" 

