---
- hosts: masters, workers
  become: yes
  remote_user: ec2-user
  tasks:
    - name: Add k8s yum repository
      blockinfile:
        path: /etc/yum.repos.d/kubernetes.repo
        create: yes
        block: |
              [kubernetes]
              baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
              enabled=1
              gpgcheck=1
              gpgkey=https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

    - name: yum - Install containerd
      yum: 
        name: 'containerd'
        state: latest
        update_cache: yes

    - name: Enable IPv4 Forwarding and enable iptables to see bridged traffic
      blockinfile:
        path: /etc/modules-load.d/k8s.conf
        create: yes
        block: |
              overlay
              br_netfilter

    - name: Start modprobe overlay and br_netfilter
      shell: |
            modprobe overlay
            modprobe br_netfilter

    - name: Updating sysctl parameters k8s.conf file
      blockinfile:
        path: /etc/sysctl.d/k8s.conf
        create: yes
        block: |
              net.bridge.bridge-nf-call-iptables  = 1
              net.bridge.bridge-nf-call-ip6tables = 1
              net.ipv4.ip_forward                 = 1
  
    - name: Apply sysctl parameters w/o reboot
      shell: |
              sysctl --system

    - name: Disable swap
      shell: |
            swapoff -a
            sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
    
    - name: yum - Install kubelet
      yum:
        name: kubelet-1.24.7
        state: latest
        update_cache: yes

    - name: Enable kubelet via systemctl
      shell: |
            systemctl enable --now kubelet

    - name: Start containerd
      systemd:
        state: started
        name: containerd