---
- hosts: masters
  become: yes
  remote_user: ec2-user
  tasks:
  - name: yum - Install kubeadm
    yum:
      name: kubeadm
      state: latest
      update_cache: yes
  
  - name: yum - Install kubectl
    yum:
      name: kubectl
      state: latest
      update_cache: yes
  
  - name: k8s - Initialize cluster
    shell: kubeadm init --pod-network-cidr=192.168.0.0/16

  - name: Creating .kube directory for ec2-user
    file:
      path: /home/ec2-user/.kube
      state: directory
      mode: 0755
      owner: ec2-user
      group: ec2-user

  - name: Copying admin.conf to ec2-user directory
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/ec2-user/.kube/config
      remote_src: yes
      owner: ec2-user
      group: ec2-user

  - name: Pausing for 10 seconds before deploying pod network
    pause:
      seconds: 10

  - name: Installing calico pod network
    become: yes
    become_user: ec2-user
    shell: |
          kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/tigera-operator.yaml
          kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/custom-resources.yaml
    
    
